import{a as h,S as g,i as n}from"./assets/vendor-Bbte2Oa8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();async function d(e,r=1,a=15){return(await h.get("https://pixabay.com/api/",{params:{page:r,per_page:a,key:"57644288-12613f747784ed1ecbf29c2c7",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const u=new g(".gallery a",{captionsData:"alt",captionDelay:250});function f(e){const r=document.querySelector(".gallery"),a=e.map(s=>`
        <li class="gallery-item">
          <a href="${s.largeImageURL}" target="_blank"><img src="${s.webformatURL}" alt="${s.tags}" /></a>
          <div>
            <p>Likes: ${s.likes}</p>
            <p>Views: ${s.views}</p>
            <p>Comments: ${s.comments}</p>
            <p>Downloads: ${s.downloads}</p>
          </div>
        </li>
      `).join("");r.insertAdjacentHTML("beforeend",a),u.refresh()}function L(){const e=document.querySelector(".gallery");e.innerHTML="",u.refresh()}function m(){document.querySelector(".loader").classList.add("block")}function y(){document.querySelector(".loader").classList.remove("block")}function b(){document.querySelector(".load-more").classList.add("block")}function p(){document.querySelector(".load-more").classList.remove("block")}let c="",l=1;const w=document.querySelector(".form"),S=document.querySelector(".load-more");w.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements["search-text"].value.trim(),l=1,c===""){n.error({title:"Error",message:"Please enter a search query"});return}L(),m();try{const r=await d(c,l);if(r.hits.length===0)return n.error({title:"Error",message:"No images found for this query"});f(r.hits),r.totalHits>15?b():p()}catch{n.error({title:"Error",message:"Failed to fetch images"})}finally{y()}});S.addEventListener("click",async()=>{l++,m();try{const e=await d(c,l);f(e.hits),e.totalHits<15*l&&(n.error({title:"Error",message:"We're sorry, but you've reached the end of search results."}),p());const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch{n.error({title:"Error",message:"Failed to fetch images"})}finally{y()}});
//# sourceMappingURL=index.js.map
